/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public String getGreeting2() {
    return "Sum of 2 and 3 is 5. Average is 2.5.";
  }

  public String getGreeting3() {
    return "Sum of 1 to 10 is 55. Average is 5.5.";
  }

  public String getGreeting4() {
    return "Sum of odd of 1 to 10 is 25. Sum of even is 30.";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    System.out.println(new App().getGreeting2());
    System.out.println(new App().getGreeting3());
    System.out.println(new App().getGreeting4());

  }
}
