/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
  @Test
  public void testAppReternHelloWorld() {
    App classUnderTest = new App();
    assertEquals("Hello World!", classUnderTest.getGreeting());
    assertEquals("Hello World!", classUnderTest.getGreeting2());
    assertEquals("Hello World!", classUnderTest.getGreeting3());
    assertEquals("Hello World!", classUnderTest.getGreeting4());
    /* “Hello World!”->“Hello World”に変更 */
  }
}
